# Generated by Django 4.0.4 on 2022-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='img',
            field=models.ImageField(default=1, upload_to='st-fb/'),
            preserve_default=False,
        ),
    ]
